import {User, PostInterface} from './types';

export const MOCK_USERS: User[] = [
  {
    name: 'andrea.schmidt',
    profile_picture: 'https://picsum.photos/200',
    bio: 'I love traveling :)',
    followersCount: 2432,
    followingCount: 1200,
    postsCount: 64,
    following: false,
    isFollowingMe: true,
    online: false,
  },
  {
    name: 'monicaa',
    profile_picture: 'https://picsum.photos/201',
    bio: 'Out on an adventure',
    followersCount: 2432,
    followingCount: 1200,
    postsCount: 64,
    following: false,
    isFollowingMe: true,
    online: false,
  },
  {
    profile_picture: 'https://picsum.photos/202',
    name: 'John Smith',
    following: false,
    isFollowingMe: false,
    online: false,
    bio: 'Out on an adventure',
    followersCount: 2432,
    followingCount: 1200,
    postsCount: 64,
  },
  {
    profile_picture: 'https://picsum.photos/203',
    name: 'Jane Smith',
    following: true,
    isFollowingMe: true,
    online: true,
    bio: 'Out on an adventure',
    followersCount: 2432,
    followingCount: 1200,
    postsCount: 64,
  },
  {
    profile_picture: 'https://picsum.photos/204',
    name: 'Brad Pitt',
    following: false,
    isFollowingMe: true,
    online: false,
    bio: '😎',
    followersCount: 2432,
    followingCount: 1200,
    postsCount: 64,
  },
  {
    profile_picture: 'https://picsum.photos/205',
    name: 'Robert Downey Jr',
    following: false,
    isFollowingMe: true,
    online: false,
    bio: 'The real life Tony Stark',
    followersCount: 10000000,
    followingCount: 2400,
    postsCount: 1000,
  },
  {
    profile_picture: 'https://picsum.photos/206',
    name: 'Tony Stark',
    following: false,
    isFollowingMe: false,
    online: true,
    bio: 'I am IronMan',
    followersCount: 1234,
    followingCount: 240,
    postsCount: 120,
  },
  {
    profile_picture: 'https://picsum.photos/207',
    name: 'Marco Polo',
    following: false,
    isFollowingMe: false,
    online: false,
    bio: 'Where are you?',
    followersCount: 10000,
    followingCount: 2223,
    postsCount: 12,
  },
];

export const posts: PostInterface[] = [
  {
    id: 'ffbeb717-9ffb-4a83-9b71-d47a90b57f60',
    user: {
      ...MOCK_USERS[0],
    },
    image: {
      uri: 'https://picsum.photos/900',
    },
    caption: '🇨🇭 Beautiful Zürich Switzerland',
    timestamp: 1514764800,
    comments: ['andrea.schmidt', 'monicaa', 'alexandergarcia', 'jmitch'],
    likes: 42,
  },
  {
    id: 'f5fasd829-951e-4d32-a400-0c6a097dd29d',
    user: {
      ...MOCK_USERS[1],
    },
    image: {
      uri: 'https://picsum.photos/900',
    },
    caption: 'Finding Balance',
    timestamp: 1514769900,
    likes: 24,
    comments: [],
  },
  {
    id: 'f5f09829-951e-4d32-a400-0c6asdf97dd29d',
    user: {
      ...MOCK_USERS[2],
    },
    image: {
      uri: 'https://picsum.photos/900',
    },
    caption: 'Finding Balance',
    timestamp: 1514769900,
    likes: 24,
    comments: [],
  },
  {
    id: 'f5fxcv829-951e-4d32-a423-0c6a097dd29d',
    user: {
      ...MOCK_USERS[3],
    },
    image: {
      uri: 'https://picsum.photos/900',
    },
    caption: 'Finding Balance',
    timestamp: 1514769900,
    likes: 24,
    comments: [],
  },
  {
    id: 'f5f09829-121e-4d32-a400-0c623497dd29d',
    user: {
      ...MOCK_USERS[4],
    },
    image: {
      uri: 'https://picsum.photos/900',
    },
    caption: 'Finding Balance',
    timestamp: 1514769900,
    likes: 24,
    comments: [],
  },
];
